language: python

python:
- "2.7"
- "3.6"
- "3.7"
- "3.8-dev"

install:
- pip install -r tests/requirements.txt

script:
- export PYTHONPATH=$PYTHONPATH:.
- py.test tests --cov uuid64 --cov-report term-missing

after_success:
- coveralls
